export const FETCH_ALL_VOTERS_REQUEST = 'FETCH_ALL_VOTERS_REQUEST';
export const FETCH_ALL_VOTERS_SUCCESS = 'FETCH_ALL_VOTERS_SUCCESS';
export const FETCH_ALL_VOTERS_FAILURE = 'FETCH_ALL_VOTERS_FAILURE';

export const SEARCH_BY_NAME_REQUEST = 'SEARCH_BY_NAME_REQUEST';
export const SEARCH_BY_NAME_SUCCESS = 'SEARCH_BY_NAME_SUCCESS';
export const SEARCH_BY_NAME_FAILURE = 'SEARCH_BY_NAME_FAILURE';

export const FILTER_BY_CASTED_STATUS_REQUEST = 'FILTER_BY_CASTED_STATUS_REQUEST';
export const FILTER_BY_CASTED_STATUS_SUCCESS = 'FILTER_BY_CASTED_STATUS_SUCCESS';
export const FILTER_BY_CASTED_STATUS_FAILURE = 'FILTER_BY_CASTED_STATUS_FAILURE';
